"""Add BotConfig and Trade models

Revision ID: 4bbba8b81c22
Revises: d5100eca417b
Create Date: 2026-02-24 10:10:54.751856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bbba8b81c22'
down_revision: Union[str, Sequence[str], None] = 'd5100eca417b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('strategy_type', sa.Enum('GRID', 'HEDGE', 'NEUTRAL', name='strategy_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('IDLE', 'STARTING', 'RUNNING', 'PAUSED', 'STOPPING', 'STOPPED', 'ERROR', name='bot_status_enum'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('base_asset', sa.String(length=20), nullable=False),
    sa.Column('quote_asset', sa.String(length=20), nullable=False),
    sa.Column('total_investment', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('is_testnet', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_configs_id'), 'bot_configs', ['id'], unique=False)
    op.create_index(op.f('ix_bot_configs_symbol'), 'bot_configs', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('bot_config_id', sa.Integer(), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=100), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='order_side_enum'), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('executed_qty', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'PARTIALLY_FILLED', 'FILLED', 'CANCELED', 'REJECTED', 'EXPIRED', name='order_status_enum'), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee_asset', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bot_config_id'], ['bot_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_exchange_order_id'), 'trades', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_index(op.f('ix_trades_exchange_order_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_bot_configs_symbol'), table_name='bot_configs')
    op.drop_index(op.f('ix_bot_configs_id'), table_name='bot_configs')
    op.drop_table('bot_configs')
    # ### end Alembic commands ###
